/*
 * C# Parser Microservice API
 *
 * A generic REST API for C# code analysis. Provides endpoints to extract code structure, entities, and relationships from C# source files.
 *
 * OpenAPI spec version: 1.0.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace OLLAMACHAT.Generated.Models
{
    /// <summary>
    /// High-level metadata about the parsed file.
    /// </summary>
    [DataContract]
    public partial class FileMetadataDto : IEquatable<FileMetadataDto>
    {
        /// <summary>
        /// Lines of Code.
        /// </summary>
        /// <value>Lines of Code.</value>

        [DataMember(Name="loc")]
        public int? Loc { get; set; }

        /// <summary>
        /// Aggregated cyclomatic complexity.
        /// </summary>
        /// <value>Aggregated cyclomatic complexity.</value>

        [DataMember(Name="complexityScore")]
        public int? ComplexityScore { get; set; }

        /// <summary>
        /// The primary namespace of the file.
        /// </summary>
        /// <value>The primary namespace of the file.</value>

        [DataMember(Name="namespace")]
        public string Namespace { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class FileMetadata {\n");
            sb.Append("  Loc: ").Append(Loc).Append("\n");
            sb.Append("  ComplexityScore: ").Append(ComplexityScore).Append("\n");
            sb.Append("  _Namespace: ").Append(Namespace).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((FileMetadataDto)obj);
        }

        /// <summary>
        /// Returns true if FileMetadata instances are equal
        /// </summary>
        /// <param name="other">Instance of FileMetadata to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(FileMetadataDto other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return
                (
                    Loc == other.Loc ||
                    Loc != null &&
                    Loc.Equals(other.Loc)
                ) &&
                (
                    ComplexityScore == other.ComplexityScore ||
                    ComplexityScore != null &&
                    ComplexityScore.Equals(other.ComplexityScore)
                ) &&
                (
                    Namespace == other.Namespace ||
                    Namespace != null &&
                    Namespace.Equals(other.Namespace)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Loc != null)
                    hashCode = hashCode * 59 + Loc.GetHashCode();
                    if (ComplexityScore != null)
                    hashCode = hashCode * 59 + ComplexityScore.GetHashCode();
                    if (Namespace != null)
                    hashCode = hashCode * 59 + Namespace.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(FileMetadataDto left, FileMetadataDto right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(FileMetadataDto left, FileMetadataDto right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
