/*
 * C# Parser Microservice API
 *
 * A generic REST API for C# code analysis. Provides endpoints to extract code structure, entities, and relationships from C# source files.
 *
 * OpenAPI spec version: 1.0.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using Newtonsoft.Json;

namespace OLLAMACHAT.Generated.Models
{
    /// <summary>
    /// Represents a single parsed code entity (class, method, etc.).
    /// </summary>
    [DataContract]
    public partial class ParsedEntityDto : IEquatable<ParsedEntityDto>
    {
        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [Required]

        [DataMember(Name="name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        [XmlType("OLLAMACHAT.Generated.Models.ParsedEntityDto.TypeEnumDto")]
        public enum TypeEnumDto
        {
            /// <summary>
            /// Enum ClassEnum for class
            /// </summary>
            [EnumMember(Value = "class")]
            ClassEnum = 0,
            /// <summary>
            /// Enum MethodEnum for method
            /// </summary>
            [EnumMember(Value = "method")]
            MethodEnum = 1,
            /// <summary>
            /// Enum InterfaceEnum for interface
            /// </summary>
            [EnumMember(Value = "interface")]
            InterfaceEnum = 2,
            /// <summary>
            /// Enum ImportEnum for import
            /// </summary>
            [EnumMember(Value = "import")]
            ImportEnum = 3,
            /// <summary>
            /// Enum PropertyEnum for property
            /// </summary>
            [EnumMember(Value = "property")]
            PropertyEnum = 4,
            /// <summary>
            /// Enum EnumEnum for enum
            /// </summary>
            [EnumMember(Value = "enum")]
            EnumEnum = 5,
            /// <summary>
            /// Enum StructEnum for struct
            /// </summary>
            [EnumMember(Value = "struct")]
            StructEnum = 6,
            /// <summary>
            /// Enum NamespaceEnum for namespace
            /// </summary>
            [EnumMember(Value = "namespace")]
            NamespaceEnum = 7        }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [Required]

        [DataMember(Name="type")]
        public TypeEnumDto? Type { get; set; }

        /// <summary>
        /// Gets or Sets Location
        /// </summary>
        [Required]

        [DataMember(Name="location")]
        public LocationDto Location { get; set; }

        /// <summary>
        /// Gets or Sets Children
        /// </summary>

        [DataMember(Name="children")]
        public List<ParsedEntityDto> Children { get; set; }

        /// <summary>
        /// Gets or Sets Modifiers
        /// </summary>

        [DataMember(Name="modifiers")]
        public List<string> Modifiers { get; set; }

        /// <summary>
        /// Gets or Sets Decorators
        /// </summary>

        [DataMember(Name="decorators")]
        public List<DecoratorDto> Decorators { get; set; }

        /// <summary>
        /// Gets or Sets Inheritance
        /// </summary>

        [DataMember(Name="inheritance")]
        public ParsedEntityInheritanceDto Inheritance { get; set; }

        /// <summary>
        /// Gets or Sets ReturnType
        /// </summary>

        [DataMember(Name="returnType")]
        public string ReturnType { get; set; }

        /// <summary>
        /// Gets or Sets Parameters
        /// </summary>

        [DataMember(Name="parameters")]
        public List<ModelParameterDto> Parameters { get; set; }

        /// <summary>
        /// Gets or Sets ImportData
        /// </summary>

        [DataMember(Name="importData")]
        public ParsedEntityImportDataDto ImportData { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ParsedEntity {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Location: ").Append(Location).Append("\n");
            sb.Append("  Children: ").Append(Children).Append("\n");
            sb.Append("  Modifiers: ").Append(Modifiers).Append("\n");
            sb.Append("  Decorators: ").Append(Decorators).Append("\n");
            sb.Append("  Inheritance: ").Append(Inheritance).Append("\n");
            sb.Append("  ReturnType: ").Append(ReturnType).Append("\n");
            sb.Append("  Parameters: ").Append(Parameters).Append("\n");
            sb.Append("  ImportData: ").Append(ImportData).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((ParsedEntityDto)obj);
        }

        /// <summary>
        /// Returns true if ParsedEntity instances are equal
        /// </summary>
        /// <param name="other">Instance of ParsedEntity to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ParsedEntityDto other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return
                (
                    Name == other.Name ||
                    Name != null &&
                    Name.Equals(other.Name)
                ) &&
                (
                    Type == other.Type ||
                    Type != null &&
                    Type.Equals(other.Type)
                ) &&
                (
                    Location == other.Location ||
                    Location != null &&
                    Location.Equals(other.Location)
                ) &&
                (
                    Children == other.Children ||
                    Children != null &&
                    Children.SequenceEqual(other.Children)
                ) &&
                (
                    Modifiers == other.Modifiers ||
                    Modifiers != null &&
                    Modifiers.SequenceEqual(other.Modifiers)
                ) &&
                (
                    Decorators == other.Decorators ||
                    Decorators != null &&
                    Decorators.SequenceEqual(other.Decorators)
                ) &&
                (
                    Inheritance == other.Inheritance ||
                    Inheritance != null &&
                    Inheritance.Equals(other.Inheritance)
                ) &&
                (
                    ReturnType == other.ReturnType ||
                    ReturnType != null &&
                    ReturnType.Equals(other.ReturnType)
                ) &&
                (
                    Parameters == other.Parameters ||
                    Parameters != null &&
                    Parameters.SequenceEqual(other.Parameters)
                ) &&
                (
                    ImportData == other.ImportData ||
                    ImportData != null &&
                    ImportData.Equals(other.ImportData)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Name != null)
                    hashCode = hashCode * 59 + Name.GetHashCode();
                    if (Type != null)
                    hashCode = hashCode * 59 + Type.GetHashCode();
                    if (Location != null)
                    hashCode = hashCode * 59 + Location.GetHashCode();
                    if (Children != null)
                    hashCode = hashCode * 59 + Children.GetHashCode();
                    if (Modifiers != null)
                    hashCode = hashCode * 59 + Modifiers.GetHashCode();
                    if (Decorators != null)
                    hashCode = hashCode * 59 + Decorators.GetHashCode();
                    if (Inheritance != null)
                    hashCode = hashCode * 59 + Inheritance.GetHashCode();
                    if (ReturnType != null)
                    hashCode = hashCode * 59 + ReturnType.GetHashCode();
                    if (Parameters != null)
                    hashCode = hashCode * 59 + Parameters.GetHashCode();
                    if (ImportData != null)
                    hashCode = hashCode * 59 + ImportData.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(ParsedEntityDto left, ParsedEntityDto right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(ParsedEntityDto left, ParsedEntityDto right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
