/*
 * C# Parser Microservice API
 *
 * A generic REST API for C# code analysis. Provides endpoints to extract code structure, entities, and relationships from C# source files.
 *
 * OpenAPI spec version: 1.0.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using Newtonsoft.Json;

namespace OLLAMACHAT.Generated.Models
{
    /// <summary>
    /// Represents a relationship between two entities.
    /// </summary>
    [DataContract]
    public partial class Relationship : IEquatable<Relationship>
    {
        /// <summary>
        /// Name of the source entity.
        /// </summary>
        /// <value>Name of the source entity.</value>
        [Required]

        [DataMember(Name="from")]
        public string From { get; set; }

        /// <summary>
        /// Name of the target entity.
        /// </summary>
        /// <value>Name of the target entity.</value>
        [Required]

        [DataMember(Name="to")]
        public string To { get; set; }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        [XmlType("OLLAMACHAT.Generated.Models.Relationship.TypeEnum")]
        public enum TypeEnum
        {
            /// <summary>
            /// Enum InheritsEnum for inherits
            /// </summary>
            [EnumMember(Value = "inherits")]
            InheritsEnum = 0,
            /// <summary>
            /// Enum ImplementsEnum for implements
            /// </summary>
            [EnumMember(Value = "implements")]
            ImplementsEnum = 1,
            /// <summary>
            /// Enum CallsEnum for calls
            /// </summary>
            [EnumMember(Value = "calls")]
            CallsEnum = 2,
            /// <summary>
            /// Enum ReferencesEnum for references
            /// </summary>
            [EnumMember(Value = "references")]
            ReferencesEnum = 3        }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [Required]

        [DataMember(Name="type")]
        public TypeEnum? Type { get; set; }

        /// <summary>
        /// Relative path to the target file if the relationship is cross-file.
        /// </summary>
        /// <value>Relative path to the target file if the relationship is cross-file.</value>

        [DataMember(Name="targetFile")]
        public string TargetFile { get; set; }

        /// <summary>
        /// Gets or Sets Location
        /// </summary>

        [DataMember(Name="location")]
        public Location Location { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Relationship {\n");
            sb.Append("  From: ").Append(From).Append("\n");
            sb.Append("  To: ").Append(To).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  TargetFile: ").Append(TargetFile).Append("\n");
            sb.Append("  Location: ").Append(Location).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((Relationship)obj);
        }

        /// <summary>
        /// Returns true if Relationship instances are equal
        /// </summary>
        /// <param name="other">Instance of Relationship to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Relationship other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return
                (
                    From == other.From ||
                    From != null &&
                    From.Equals(other.From)
                ) &&
                (
                    To == other.To ||
                    To != null &&
                    To.Equals(other.To)
                ) &&
                (
                    Type == other.Type ||
                    Type != null &&
                    Type.Equals(other.Type)
                ) &&
                (
                    TargetFile == other.TargetFile ||
                    TargetFile != null &&
                    TargetFile.Equals(other.TargetFile)
                ) &&
                (
                    Location == other.Location ||
                    Location != null &&
                    Location.Equals(other.Location)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (From != null)
                    hashCode = hashCode * 59 + From.GetHashCode();
                    if (To != null)
                    hashCode = hashCode * 59 + To.GetHashCode();
                    if (Type != null)
                    hashCode = hashCode * 59 + Type.GetHashCode();
                    if (TargetFile != null)
                    hashCode = hashCode * 59 + TargetFile.GetHashCode();
                    if (Location != null)
                    hashCode = hashCode * 59 + Location.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(Relationship left, Relationship right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(Relationship left, Relationship right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
