// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VelikiyPrikalel.OLLAMACHAT.Infrastructure.Data;

#nullable disable

namespace VelikiyPrikalel.OLLAMACHAT.Infrastructure.Context.Migrations
{
    [DbContext(typeof(OllamaChatContext))]
    [Migration("20251010214219_UnityModels")]
    partial class UnityModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.16");

            modelBuilder.Entity("VelikiyPrikalel.OLLAMACHAT.Data.Llm.ChatMessage", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChatId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("Time")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("VelikiyPrikalel.OLLAMACHAT.Data.Llm.User", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("VelikiyPrikalel.OLLAMACHAT.Data.Llm.UserChat", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserChats");
                });

            modelBuilder.Entity("VelikiyPrikalel.OLLAMACHAT.Data.Parser.EventHandler", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ArgumentsHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseClassFullName")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsInherited")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("ParameterTypes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ArgumentsHash")
                        .HasDatabaseName("IX_EventHandlers_ArgumentsHash");

                    b.HasIndex("FilePath")
                        .HasDatabaseName("IX_EventHandlers_FilePath");

                    b.HasIndex("FullName")
                        .IsUnique()
                        .HasDatabaseName("IX_EventHandlers_FullName");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_EventHandlers_IsDeleted");

                    b.HasIndex("IsPublic")
                        .HasDatabaseName("IX_EventHandlers_IsPublic");

                    b.HasIndex("LastModified")
                        .HasDatabaseName("IX_EventHandlers_LastModified");

                    b.ToTable("EventHandlers");
                });

            modelBuilder.Entity("VelikiyPrikalel.OLLAMACHAT.Data.Parser.EventHandlerRelationship", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DeletionReason")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EventHandlerRelationshipType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HandlerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EventHandlerRelationshipType")
                        .HasDatabaseName("IX_EventHandlerRelationships_RelationshipType");

                    b.HasIndex("EventId")
                        .HasDatabaseName("IX_EventHandlerRelationships_EventId");

                    b.HasIndex("HandlerId")
                        .HasDatabaseName("IX_EventHandlerRelationships_HandlerId");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_EventHandlerRelationships_IsDeleted");

                    b.HasIndex("Source")
                        .HasDatabaseName("IX_EventHandlerRelationships_Source");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("IX_EventHandlerRelationships_UpdatedAt");

                    b.HasIndex("EventId", "HandlerId")
                        .IsUnique()
                        .HasDatabaseName("IX_EventHandlerRelationships_EventId_HandlerId");

                    b.ToTable("EventHandlerRelationships");
                });

            modelBuilder.Entity("VelikiyPrikalel.OLLAMACHAT.Data.Parser.UnityEvent", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ArgumentsHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseClassFullName")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("GenericTypeArguments")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsInherited")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ArgumentsHash")
                        .HasDatabaseName("IX_UnityEvents_ArgumentsHash");

                    b.HasIndex("FilePath")
                        .HasDatabaseName("IX_UnityEvents_FilePath");

                    b.HasIndex("FullName")
                        .IsUnique()
                        .HasDatabaseName("IX_UnityEvents_FullName");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_UnityEvents_IsDeleted");

                    b.HasIndex("LastModified")
                        .HasDatabaseName("IX_UnityEvents_LastModified");

                    b.ToTable("UnityEvents");
                });

            modelBuilder.Entity("VelikiyPrikalel.OLLAMACHAT.Data.Llm.ChatMessage", b =>
                {
                    b.HasOne("VelikiyPrikalel.OLLAMACHAT.Data.Llm.UserChat", null)
                        .WithMany("Messages")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VelikiyPrikalel.OLLAMACHAT.Data.Llm.UserChat", b =>
                {
                    b.HasOne("VelikiyPrikalel.OLLAMACHAT.Data.Llm.User", null)
                        .WithMany("Chats")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VelikiyPrikalel.OLLAMACHAT.Data.Parser.EventHandlerRelationship", b =>
                {
                    b.HasOne("VelikiyPrikalel.OLLAMACHAT.Data.Parser.UnityEvent", "Event")
                        .WithMany("HandlerRelationships")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VelikiyPrikalel.OLLAMACHAT.Data.Parser.EventHandler", "Handler")
                        .WithMany("EventRelationships")
                        .HasForeignKey("HandlerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Handler");
                });

            modelBuilder.Entity("VelikiyPrikalel.OLLAMACHAT.Data.Llm.User", b =>
                {
                    b.Navigation("Chats");
                });

            modelBuilder.Entity("VelikiyPrikalel.OLLAMACHAT.Data.Llm.UserChat", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("VelikiyPrikalel.OLLAMACHAT.Data.Parser.EventHandler", b =>
                {
                    b.Navigation("EventRelationships");
                });

            modelBuilder.Entity("VelikiyPrikalel.OLLAMACHAT.Data.Parser.UnityEvent", b =>
                {
                    b.Navigation("HandlerRelationships");
                });
#pragma warning restore 612, 618
        }
    }
}
