/*
 * C# Parser Microservice API
 *
 * A generic REST API for C# code analysis. Provides endpoints to extract code structure, entities, and relationships from C# source files.
 *
 * OpenAPI spec version: 1.0.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
namespace OLLAMACHAT.Generated.Models.ParseResponse;

/// <summary>
///
/// </summary>
[DataContract]
public partial class ModelParameterDto : IEquatable<ModelParameterDto>
{
    /// <summary>
    /// Gets or Sets Name
    /// </summary>

    [DataMember(Name="name")]
    public string Name { get; set; }

    /// <summary>
    /// Gets or Sets Type
    /// </summary>

    [DataMember(Name="type")]
    public string Type { get; set; }

    /// <summary>
    /// Gets or Sets Optional
    /// </summary>

    [DataMember(Name="optional")]
    public bool? Optional { get; set; }

    /// <summary>
    /// Gets or Sets DefaultValue
    /// </summary>

    [DataMember(Name="defaultValue")]
    public string DefaultValue { get; set; }

    /// <summary>
    /// Returns the string presentation of the object
    /// </summary>
    /// <returns>String presentation of the object</returns>
    public override string ToString()
    {
        var sb = new StringBuilder();
        sb.Append("class ModelParameter {\n");
        sb.Append("  Name: ").Append(Name).Append("\n");
        sb.Append("  Type: ").Append(Type).Append("\n");
        sb.Append("  Optional: ").Append(Optional).Append("\n");
        sb.Append("  DefaultValue: ").Append(DefaultValue).Append("\n");
        sb.Append("}\n");
        return sb.ToString();
    }

    /// <summary>
    /// Returns the JSON string presentation of the object
    /// </summary>
    /// <returns>JSON string presentation of the object</returns>
    public string ToJson()
    {
        return JsonConvert.SerializeObject(this, Formatting.Indented);
    }

    /// <summary>
    /// Returns true if objects are equal
    /// </summary>
    /// <param name="obj">Object to be compared</param>
    /// <returns>Boolean</returns>
    public override bool Equals(object obj)
    {
        if (ReferenceEquals(null, obj)) return false;
        if (ReferenceEquals(this, obj)) return true;
        return obj.GetType() == GetType() && Equals((ModelParameterDto)obj);
    }

    /// <summary>
    /// Returns true if ModelParameter instances are equal
    /// </summary>
    /// <param name="other">Instance of ModelParameter to be compared</param>
    /// <returns>Boolean</returns>
    public bool Equals(ModelParameterDto other)
    {
        if (ReferenceEquals(null, other)) return false;
        if (ReferenceEquals(this, other)) return true;

        return
            (
                Name == other.Name ||
                Name != null &&
                Name.Equals(other.Name)
            ) &&
            (
                Type == other.Type ||
                Type != null &&
                Type.Equals(other.Type)
            ) &&
            (
                Optional == other.Optional ||
                Optional != null &&
                Optional.Equals(other.Optional)
            ) &&
            (
                DefaultValue == other.DefaultValue ||
                DefaultValue != null &&
                DefaultValue.Equals(other.DefaultValue)
            );
    }

    /// <summary>
    /// Gets the hash code
    /// </summary>
    /// <returns>Hash code</returns>
    public override int GetHashCode()
    {
        unchecked // Overflow is fine, just wrap
        {
            var hashCode = 41;
            // Suitable nullity checks etc, of course :)
            if (Name != null)
                hashCode = hashCode * 59 + Name.GetHashCode();
            if (Type != null)
                hashCode = hashCode * 59 + Type.GetHashCode();
            if (Optional != null)
                hashCode = hashCode * 59 + Optional.GetHashCode();
            if (DefaultValue != null)
                hashCode = hashCode * 59 + DefaultValue.GetHashCode();
            return hashCode;
        }
    }

    #region Operators
#pragma warning disable 1591

    public static bool operator ==(ModelParameterDto left, ModelParameterDto right)
    {
        return Equals(left, right);
    }

    public static bool operator !=(ModelParameterDto left, ModelParameterDto right)
    {
        return !Equals(left, right);
    }

#pragma warning restore 1591
    #endregion Operators
}