/*
 * C# Parser Microservice API
 *
 * A generic REST API for C# code analysis. Provides endpoints to extract code structure, entities, and relationships from C# source files.
 *
 * OpenAPI spec version: 1.0.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
namespace OLLAMACHAT.Generated.Models.ParseResponse;

/// <summary>
/// 
/// </summary>
[DataContract]
public partial class ParsedEntityInheritanceDto : IEquatable<ParsedEntityInheritanceDto>
{ 
    /// <summary>
    /// Gets or Sets BaseClasses
    /// </summary>

    [DataMember(Name="baseClasses")]
    public List<string> BaseClasses { get; set; }

    /// <summary>
    /// Gets or Sets Interfaces
    /// </summary>

    [DataMember(Name="interfaces")]
    public List<string> Interfaces { get; set; }

    /// <summary>
    /// Returns the string presentation of the object
    /// </summary>
    /// <returns>String presentation of the object</returns>
    public override string ToString()
    {
        var sb = new StringBuilder();
        sb.Append("class ParsedEntityInheritance {\n");
        sb.Append("  BaseClasses: ").Append(BaseClasses).Append("\n");
        sb.Append("  Interfaces: ").Append(Interfaces).Append("\n");
        sb.Append("}\n");
        return sb.ToString();
    }

    /// <summary>
    /// Returns the JSON string presentation of the object
    /// </summary>
    /// <returns>JSON string presentation of the object</returns>
    public string ToJson()
    {
        return JsonConvert.SerializeObject(this, Formatting.Indented);
    }

    /// <summary>
    /// Returns true if objects are equal
    /// </summary>
    /// <param name="obj">Object to be compared</param>
    /// <returns>Boolean</returns>
    public override bool Equals(object obj)
    {
        if (ReferenceEquals(null, obj)) return false;
        if (ReferenceEquals(this, obj)) return true;
        return obj.GetType() == GetType() && Equals((ParsedEntityInheritanceDto)obj);
    }

    /// <summary>
    /// Returns true if ParsedEntityInheritance instances are equal
    /// </summary>
    /// <param name="other">Instance of ParsedEntityInheritance to be compared</param>
    /// <returns>Boolean</returns>
    public bool Equals(ParsedEntityInheritanceDto other)
    {
        if (ReferenceEquals(null, other)) return false;
        if (ReferenceEquals(this, other)) return true;

        return 
            (
                BaseClasses == other.BaseClasses ||
                BaseClasses != null &&
                BaseClasses.SequenceEqual(other.BaseClasses)
            ) && 
            (
                Interfaces == other.Interfaces ||
                Interfaces != null &&
                Interfaces.SequenceEqual(other.Interfaces)
            );
    }

    /// <summary>
    /// Gets the hash code
    /// </summary>
    /// <returns>Hash code</returns>
    public override int GetHashCode()
    {
        unchecked // Overflow is fine, just wrap
        {
            var hashCode = 41;
            // Suitable nullity checks etc, of course :)
            if (BaseClasses != null)
                hashCode = hashCode * 59 + BaseClasses.GetHashCode();
            if (Interfaces != null)
                hashCode = hashCode * 59 + Interfaces.GetHashCode();
            return hashCode;
        }
    }

    #region Operators
#pragma warning disable 1591

    public static bool operator ==(ParsedEntityInheritanceDto left, ParsedEntityInheritanceDto right)
    {
        return Equals(left, right);
    }

    public static bool operator !=(ParsedEntityInheritanceDto left, ParsedEntityInheritanceDto right)
    {
        return !Equals(left, right);
    }

#pragma warning restore 1591
    #endregion Operators
}