// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VelikiyPrikalel.OLLAMACHAT.Infrastructure.Data;

#nullable disable

namespace VelikiyPrikalel.OLLAMACHAT.Infrastructure.Data.Migrations
{
    [DbContext(typeof(OllamaChatContext))]
    partial class OllamaChatContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VelikiyPrikalel.OLLAMACHAT.Data.ChatMessage", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ChatId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("Time")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserChatId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserChatId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("VelikiyPrikalel.OLLAMACHAT.Data.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("VelikiyPrikalel.OLLAMACHAT.Data.UserChat", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserChats");
                });

            modelBuilder.Entity("VelikiyPrikalel.OLLAMACHAT.Data.ChatMessage", b =>
                {
                    b.HasOne("VelikiyPrikalel.OLLAMACHAT.Data.UserChat", null)
                        .WithMany("Messages")
                        .HasForeignKey("UserChatId");
                });

            modelBuilder.Entity("VelikiyPrikalel.OLLAMACHAT.Data.UserChat", b =>
                {
                    b.HasOne("VelikiyPrikalel.OLLAMACHAT.Data.User", null)
                        .WithMany("Chats")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VelikiyPrikalel.OLLAMACHAT.Data.User", b =>
                {
                    b.Navigation("Chats");
                });

            modelBuilder.Entity("VelikiyPrikalel.OLLAMACHAT.Data.UserChat", b =>
                {
                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
